 logs:
   configs:
     - name: default
       positions:
         filename: /tmp/positions.yaml
       scrape_configs:
         - job_name: zksync-remix-docker-logs
           static_configs:
             - targets: [localhost]
               labels:
                 job: zksync-remix-docker-logs
                 __path__: "${PROMTAIL_BASE_DIR}/logs/*"
       clients:
         - url: https://logs-prod-us-central1.grafana.net/loki/api/v1/push
           basic_auth:
             username: ${PROMTAIL_USERNAME}
             password: ${PROMTAIL_PASSWORD}
